#!/bin/bash
# =============================== TEST SIMULATION =========================================
# Passar como parametro o id do metodo, as velocidades na rede de Purkinje e no endocardio,
# e o caminho para o arquivo .vtk
# =========================================================================================

if [ $# == 4 ]; then
	METODO=$1
	V_PK=$2
	V_ENDO=$3
    PATH_VTK=$4
    if [ $METODO == 1 ]; then
        echo "Running Benjamin's simulation"
    elif [ $METODO == 2 ]; then
        echo "Running CCO simulation"
    else
        echo "Running L-System simulation"
    fi
    # make
    # ./executa_FMM <v_pk> <v_endo> <path_to_vtk>
    #echo $1
    #echo $2
    #echo $3
    #echo $4
else
    echo "================================================================================"
	echo "Usage:> $0 <id_metodo> <v_pk> <v_endo> <path_to_vtk>"
    echo "<id_metodo> = 1 = Benjamin's Mesh"  
    echo -e "\t      2 = CCO"
    echo -e "\t      3 = L-System"
    echo "<v_pk> = Velocidade na rede de Purkinje"
    echo "<v_endo> = Velocidade no endocardio"
    echo "<path_to_vtk> = Caminho completo para o .vtk utilizado"
    echo "================================================================================"
	exit
fi